### ISSUE TITLE
404 on Issues and configure

### ISSUE THREAD

**Issue by ddanhan** [NBISweden/redmine_anonymous_watchers#2]
I made a fresh redmine installation and tried to get the plugin working, but after installation i get 404 on the plugin configure page and the issue index page.

Environment:
  Redmine version                3.4.4.stable
  Ruby version                   2.3.8-p459 (2018-10-18) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2

**Comment by nmb** [comment]
Could not reproduce in fresh docker container w/ Redmine 3.4.11-stable, SQLite db. Did you run
```
bundle install
rake redmine:plugins:migrate
```
and restart the daemon?

Also, logs (e.g. output from `$REDMINEROOT/log/production.log`) would be helpful to track down the problem.

**Comment by ddanhan** [comment]
Sorry for the circumstances. There was a typo in my plugin folder name. After fixing everything worked.

**Comment by nmb** [comment]
No worries, and thanks for the update.
